name: COVID19
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.7.*
  - attrs
  - black
  - bottleneck
  - cdsapi
  - cfgrib
  - netcdf4
  - notebook
  - pandas
  - requests
  - scipy
  - seaborn
  - xarray
